import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Footer from './components/Footer'
import Header from './components/Header'
import IntroGate from './components/IntroGate'
import MainWrapper from './components/MainWrapper'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} dark h-full antialiased`}>
      <body className="min-h-full">
        <IntroGate>
          <div className="home grid min-h-screen grid-cols-12 grid-rows-[auto_1fr_auto]">
            <Header />
            <MainWrapper>{children}</MainWrapper>
            <Footer />
          </div>
        </IntroGate>
      </body>
    </html>
  )
}
